/* eslint-disable @typescript-eslint/naming-convention */
export enum OperationTypes {
  POWER_OFF = 'OFF',
  ALL_CLEAR = 'AC',
  CLEAR = 'C',
  SQUARE_ROOT = '√',
  MEM_CLEAR = 'MC',
  MEM_RECORD = 'MR',
  MEM_ADD = 'M+',
  MEM_SUBTRACT = 'M-',
  MODULUS = '%',
  DIVISION = '÷',
  ADDITION = '+',
  SUBTRACTION = '−',
  MULTIPLICATION = '✕',
  SIGN_CHANGE = '+/-',
  DIGIT_0 = '0',
  DIGIT_1 = '1',
  DIGIT_2 = '2',
  DIGIT_3 = '3',
  DIGIT_4 = '4',
  DIGIT_5 = '5',
  DIGIT_6 = '6',
  DIGIT_7 = '7',
  DIGIT_8 = '8',
  DIGIT_9 = '9',
  FLOAT = '.',
  COMPUTE = '=',
}

export enum ActionTypes {
  DIGIT = 'DIGIT_ENTERED',
  OPERATOR = 'OPERATOR_ENTERED',
  DECIMAL_POINT = 'DECIMAL_POINT_ENTERED',
  CLEAR_EVERYTHING = 'CLEAR_EVERYTHING_ENTERED',
  PERCENTAGE = 'PERCENTAGE',
  NEGATE = 'NEGATE',
  CLEAR_ENTRY = 'CLEAR_ENTRY',
  EQUALS = 'EQUALS_PRESSED',
  POWER_OFF = 'POWER_OFF',
}
